### ISSUE TITLE
ValueError: Invalid header value b'***' (PACMAN-506)

### ISSUE THREAD

**Issue by Fishwaldo** [espressif/upload-components-ci-action#8] opened 2022-11-27 17:54 UTC
When trying to use this in a github action, I'm getting the following error:
```
Processing 1 components
Processing component "esp_ghota" at .
Saving archive to "/github/workspace/dist/esp_ghota_0.0.1.tgz"
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/site-packages/idf_component_manager/__main__.py", line 58, in <module>
    main()
  File "/usr/local/lib/python3.10/site-packages/idf_component_manager/__main__.py", line 49, in main
    getattr(manager, str(args.command).replace('-', '_'))(vars(args))
  File "/usr/local/lib/python3.10/site-packages/idf_component_manager/core.py", line 305, in upload_component
    versions = client.versions(component_name, spec='*').versions
  File "/usr/local/lib/python3.10/site-packages/idf_component_tools/api_client.py", line 196, in versions
    body = self._base_request(
  File "/usr/local/lib/python3.10/site-packages/idf_component_tools/api_client.py", line 158, in _base_request
    response = self.session.request(
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1323, in _send_request
    self.putheader(hdr, value)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 224, in putheader
    _HTTPConnection.putheader(self, header, *values)
  File "/usr/local/lib/python3.10/http/client.py", line 1260, in putheader
    raise ValueError('Invalid header value %r' % (values[i],))
ValueError: Invalid header value b'***'
An error occurred while uploading the new version of fishwaldo/esp_ghota.
```

The upload works fine from my desktop though. Any idea whats happening?

**Comment by Fishwaldo** [comment] 2022-11-27 17:55
You can see the full action log here:
https://github.com/Fishwaldo/esp_ghota/actions/runs/3559279267/jobs/5978530322

**Comment by kumekay** [comment] 2022-11-30 17:17
@Fishwaldo Thank you for the issue, we will try to reproduce and fix it.

**Comment by kumekay** [comment] 2023-01-31 16:09
@Fishwaldo Do you still have this issue? I tried to reproduce it, but it works fine even with the fork of your repo: 

https://github.com/kumekay/esp_ghota/actions/runs/4055950556/jobs/6979837162

Since this action was updated in December, could you please try restarting the job to check if the problem is still there?

**Comment by kumekay** [comment] 2023-02-27 09:43
@Fishwaldo 

I will now close this issue, but if you encounter it again, please don't hesitate to reopen it.

**Closed as completed by kumekay** 2023-02-27 09:43 UTC
Labels: bug
